### ISSUE TITLE
Propagate show options to hide too

### ISSUE THREAD

**Issue by evaldobratti** [ArthurClemens/dialogic-js#9]
I'm taking a look on how to add `primer_live` to my project and one of the issues I have is with the dialog.

The initial structure from phoenix the bootstrap it opens and hide the dialog via routes, so in my project I kept that and to migrate to `primer_live` I didn't find any other way besides using hooks.
The hook is pretty simple

```
  OpenDialog: {
    mounted() {
      Prompt.show(this.el, {didHide: () => {...somethinghere...})
    }
  }
```

but now when dialog is closed I want the callback to be called to patch live view to another route but these options from the `show` are not propagated to its internal `hide` when clicking outside or escaping, would that be possible?

If you have any other suggestions how to do this dialog opening/closing route based, taking into account that the dialog might not be ready and some data may still need to be loaded, I'm open to change my implementation as well.

Thank you so much :)

**Comment by ArthurClemens** [comment]
I see, that is an omission. Will be fixed soon.

**Comment by ArthurClemens** [comment]
I've also updated `primer-live` to 0.1.22.

**Comment by evaldobratti** [comment]
Thanks for the quick reply @ArthurClemens 

for those that might run into this issue, here is the complete hook declaration working

```
  OpenDialog: {
    mounted() {
      Prompt.show(this.el, {
        didHide: () => {
          this.liveSocket.pushHistoryPatch(this.el.dataset["returnTo"], "push", this.el)
        }
      })
    }
  }
```

and the dialog usage

```  
<.dialog phx_hook="OpenDialog" data_return_to={Routes.some_path(@socket, :index)}>
  <:body>
   Something here
  </:body>
</.dialog>
```
